language: objective-c
osx_image: xcode8

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild test -sdk iphonesimulator -scheme TodoList-iOS -destination "OS=9.3,name=iPhone 7" | xcpretty -c && exit ${PIPESTATUS[0]}

