//tealium universal tag - utag.721 ut4.0.201605272020, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.domain="";u.spacedesc="";u.db_afcr="";u.group="";u.base_url="//media."+u.domain+".com/ipixel?spacedesc="+u.spacedesc+"&db_afcr="+u.db_afcr+"&target=_blank&group="+u.group+"&";u.map={};u.extend=[function(a,b){var o=[{"page":"LP_NG_BLMX","url":"console.ng.bluemix.net/","type":"img","src":"//media.ibm.com/ping?spacedesc=9960413_1061349_1x1_1061349_1061349&db_afcr=123&group=LOB&event=LL_NG_BLMX"},{"page":"BLUEMIX LP","url":"console.ng.bluemix.net/","type":"img","src":"//media.ibm.com/ping?spacedesc=16509543_1061349_1x1_1061349_1061349&db_afcr=123&group=Q2_15Additional&event=BluemixLP"},{"page":"BluemixReg","url":"console.ng.bluemix.net/registration/","type":"img","src":"//media.ibm.com/ping?spacedesc=16509543_1061349_1x1_1061349_1061349&db_afcr=123&group=Q4AU_IDM&event=BluemixReg"}]
function getURL(h){var l=document.createElement("a");var href=h+"";if(!(href.indexOf("http")==0||href.indexOf("//")==0)){href="//"+href}l.href=href;return l};function getPath(h){var p=getURL(h).pathname+"";return((p.indexOf("/")===0)?p:"/"+p)};for(var i=0;i<o.length;i++){var t=o[i];if(b["dom.pathname"]==getPath(t.url)&&(b["dom.query_string"]==getURL(t.url).search.substring(1)||getURL(t.url).search.substring(1)==""||b["dom.query_string"].indexOf(getURL(t.url).search.substring(1))>-1)&&(b["dom.hash"]==getURL(t.url).hash.substring(1)||getURL(t.url).hash.substring(1)==""||b["dom.hash"].indexOf(getURL(t.url).hash.substring(1))>-1)){utag.DB(t);utag.ut.loader({type:t.type,src:t.src})
var collect=[];collect.push("tealium_account=ibm");collect.push("tealium_profile=main");collect.push("tealium_vid="+b["cp.utag_main_v_id"]);collect.push("event_name=beacon");var p=utag.ut.flatten(t);for(var k in p){collect.push(k+"="+encodeURIComponent(p[k]))}
collect.push("t="+encodeURIComponent(""+(new Date())));utag.ut.loader({type:"img",src:"https://collect.tealiumiq.com/vdata/i.gif?"+collect.join("&")})}}
return false;}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){c.push(e[f]+u.kvp_delim+encodeURIComponent(b[d]))}}}
if(typeof b._corder!="undefined"&&b._corder){c.push('revenue='+b._ctotal);c.push('x_orderid='+b._corder);}else{c.push('revenue=REVENUE');}
c.push('random='+Math.random());d=document.createElement("iframe");d.setAttribute('id','721');d.setAttribute('height','1');d.setAttribute('width','1');d.setAttribute('style','display:none');d.setAttribute('src',u.base_url+c.join(u.qsp_delim));document.body.appendChild(d);}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('721','ibm.main');}catch(e){}
