//tealium universal tag - utag.804 ut4.0.201605272019, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={};u.extend=[function(a,b){var o=[{"page":"IBM_PfM_Bluesky_Bluemix_IWM_GOOGLE_RMKT","url":"console.ng.bluemix.net/registration/","data":{"google_conversion_id":939297512,"google_remarketing_only":true}},{"page":"IBM_PfM_Bluesky_Bluemix_IWM_Sucess_GOOGLE_RMKT","url":"idaas.ng.bluemix.net/idaas/public/tamlogin.jsp","data":{"google_conversion_id":939297512,"google_remarketing_only":true}},{"page":"SSA_Adwords_Rmkt_tag","url":"console.ng.bluemix.net/","data":{"google_conversion_id":946896569,"google_remarketing_only":true}},{"page":"SSA_Adwords_Rmkt_tag","url":"console.ng.bluemix.net/registration/","data":{"google_conversion_id":946896569,"google_remarketing_only":true}},{"page":"Bluemix-Registration-Step-2","url":"console.ng.bluemix.net/","data":{"google_conversion_id":975533992,"google_remarketing_only":true}},{"page":"Bluemix-Confirmation-Success","url":"console.ng.bluemix.net/registration/accept","data":{"google_conversion_id":975533992,"google_remarketing_only":true}},{"page":"Bluemix-Console","url":"console.ng.bluemix.net/home/","data":{"google_conversion_id":975533992,"google_remarketing_only":true}}]
function getURL(h){var l=document.createElement("a");var href=h+"";if(!(href.indexOf("http")==0||href.indexOf("//")==0)){href="//"+href}l.href=href;return l};function getPath(h){var p=getURL(h).pathname+"";return((p.indexOf("/")===0)?p:"/"+p)};for(var i=0;i<o.length;i++){var t=o[i];if(b["dom.pathname"]==getPath(t.url)&&(b["dom.query_string"]==getURL(t.url).search.substring(1)||getURL(t.url).search.substring(1)==""||b["dom.query_string"].indexOf(getURL(t.url).search.substring(1))>-1)&&(b["dom.hash"]==getURL(t.url).hash.substring(1)||getURL(t.url).hash.substring(1)==""||b["dom.hash"].indexOf(getURL(t.url).hash.substring(1))>-1)){utag.DB(t);(function(google_conversion_id,google_remarketing_only){utag.ut.loader({type:"script",src:"//www.googleadservices.com/pagead/conversion_async.js",cb:function(){window.google_trackConversion({google_conversion_id:google_conversion_id,google_remarketing_only:google_remarketing_only});}});})(t.data.google_conversion_id,t.data.google_remarketing_only);var collect=[];collect.push("tealium_account=ibm");collect.push("tealium_profile=main");collect.push("tealium_vid="+b["cp.utag_main_v_id"]);collect.push("event_name=beacon");var p=utag.ut.flatten(t);for(var k in p){collect.push(k+"="+encodeURIComponent(p[k]))}
collect.push("t="+encodeURIComponent(""+(new Date())));utag.ut.loader({type:"img",src:"https://collect.tealiumiq.com/vdata/i.gif?"+collect.join("&")})}}
return false;}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"google_conversion_id":"","pagetype":"other","value":"","send_ecom":"yes","google_remarketing_only":true,"base_url":"//www.googleadservices.com/pagead/conversion_async.js","params":{},"product_id":[],"product_category":[],"product_quantity":[],"product_unit_price":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[],g={};var prefix="";u.data.google_custom_params={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){prefix=/^ecomm\.|^hotel\.|^edu\.|^flight\.|^hrental\.|^job\.|^local\.|^listing\.|^travel\.|^dynx\./.exec(e[f]);if(prefix!==null){prefix=prefix[0].slice(0,-1);u.data.params[prefix]=u.data.params[prefix]||{};u.data.params[prefix][e[f].substr(prefix.length+1)]=b[d];}else if(e[f].indexOf("custom.")==0){u.data.google_custom_params[e[f].substr(7)]=b[d];}else{u.data[e[f]]=b[d];}}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.google_conversion_id=parseInt(u.data.google_conversion_id);g.google_conversion_id=u.data.google_conversion_id;u.data.prod=u.data.prod||u.data.product_id;u.data.value=u.data.value||u.data.order_subtotal;for(d in u.data.params){u.data.google_custom_params[d+"_pagetype"]=u.data.pagetype;if(u.data.order_id||/purchase|conversion|cart|conversionintent/.test(u.data.pagetype)){u.data.google_custom_params[d+"_totalvalue"]=u.data.value;}
for(f in u.data.params[d]){u.data.google_custom_params[d+"_"+f]=u.data.params[d][f];}}
if(u.data.send_ecom==="yes"){if(u.data.order_id){u.data.pagetype="purchase";}
u.data.google_custom_params.ecomm_prodid=u.data.prod;u.data.google_custom_params.ecomm_pagetype=u.data.pagetype;u.data.google_custom_params.ecomm_totalvalue=u.data.value;u.data.google_custom_params.ecomm_category=u.data.google_custom_params.ecomm_category||u.data.product_category;u.data.google_custom_params.ecomm_pvalue=u.data.google_custom_params.ecomm_pvalue||u.data.product_unit_price;u.data.google_custom_params.ecomm_quantity=u.data.google_custom_params.ecomm_quantity||u.data.product_quantity;}
g.google_custom_params=u.data.google_custom_params;if(u.data.google_remarketing_only){g.google_remarketing_only=u.data.google_remarketing_only;}
u.loader_cb=function(g){u.initialized=true;window.google_trackConversion(g);};u.callBack=function(){var data={};while(data=u.queue.shift()){u.loader_cb(data.g);}};if(u.initialized){u.loader_cb(g);}else{u.queue.push({"g":g});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":'utag_804'});}}
}};utag.o[loader].loader.LOAD(id);}("804","ibm.main"));}catch(error){utag.DB(error);}
