//tealium universal tag - utag.1893 ut4.0.201605272018, Copyright 2016 Tealium.com Inc. All Rights Reserved.
if(typeof utag.ut=="undefined"){utag.ut={};}
utag.ut.libloader2=function(o,a,b,c,l){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.src=o.src;if(o.id){b.id=o.id};if(typeof o.cb=='function'){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.hFlag){b.hFlag=1;o.cb()}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb()}}}
l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){if(l=='script'){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}
utag.DB("Attach to "+l+": "+o.src)}};try{(function(id,loader,u){u=utag.o[loader].sender[id]={};u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var o=[{"page":"IBM_Q1_Spark_Bluemix_Twitter","url":"console.ng.bluemix.net/catalog/services/apache-spark/","data":{"twitter_txn_id":"nu8cz"}},{"page":"IBM_Q1_Spark_Bluemix_Registration_Twitter","url":"console.ng.bluemix.net/registration/","data":{"twitter_txn_id":"nu8cz"}},{"page":"Registration Page","url":"console.ng.bluemix.net/registration/","data":{"twitter_txn_id":"nubis"}},{"page":"Reg Step2","url":"console.ng.bluemix.net/","data":{"twitter_txn_id":"nubis"}},{"page":"Confirmation Success","url":"console.ng.bluemix.net/registration/accept","data":{"twitter_txn_id":"nubis"}},{"page":"BluemixConsole","url":"console.ng.bluemix.net/home/","data":{"twitter_txn_id":"nubis"}},{"page":"Bluemix-Registration-Step-2","url":"console.ng.bluemix.net/","data":{"twitter_txn_id":"nup6u"}},{"page":"Bluemix-Confirmation-Success","url":"console.ng.bluemix.net/registration/accept","data":{"twitter_txn_id":"nup6u"}},{"page":"Bluemix-Console","url":"console.ng.bluemix.net/home/","data":{"twitter_txn_id":"nup6u"}}]
function getURL(h){var l=document.createElement("a");var href=h+"";if(!(href.indexOf("http")==0||href.indexOf("//")==0)){href="//"+href}l.href=href;return l};function getPath(h){var p=getURL(h).pathname+"";return((p.indexOf("/")===0)?p:"/"+p)};for(var i=0;i<o.length;i++){var t=o[i];if(b["dom.pathname"]==getPath(t.url)&&(b["dom.query_string"]==getURL(t.url).search.substring(1)||getURL(t.url).search.substring(1)==""||b["dom.query_string"].indexOf(getURL(t.url).search.substring(1))>-1)&&(b["dom.hash"]==getURL(t.url).hash.substring(1)||getURL(t.url).hash.substring(1)==""||b["dom.hash"].indexOf(getURL(t.url).hash.substring(1))>-1)){utag.DB(t);(function(txn_id){utag.ut.loader({type:"script",src:"//platform.twitter.com/oct.js",cb:function(){twttr.conversion.trackPid(txn_id,{tw_sale_amount:0,tw_order_quantity:0});}});})(t.data.twitter_txn_id);var collect=[];collect.push("tealium_account=ibm");collect.push("tealium_profile=main");collect.push("tealium_vid="+b["cp.utag_main_v_id"]);collect.push("event_name=beacon");var p=utag.ut.flatten(t);for(var k in p){collect.push(k+"="+encodeURIComponent(p[k]))}
collect.push("t="+encodeURIComponent(""+(new Date())));utag.ut.loader({type:"img",src:"https://collect.tealiumiq.com/vdata/i.gif?"+collect.join("&")})}}
return false;}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f;u.data={"pid":"","base_url":"//platform.twitter.com/oct.js"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!="undefined"&&b[d]!=""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.twitter_callback=function(){u.initialized=true;twttr.conversion.trackPid(u.data.pid);};if(!u.initialized){utag.ut.libloader2({src:u.data.base_url,cb:u.twitter_callback});}else{u.twitter_callback();}
}};utag.o[loader].loader.LOAD(id);})('1893','ibm.main');}catch(e){}
